name: The name of your action here
description: Provide a description here
author: Your name or organization here

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  github-token:
    description: Token for creating release request. Recommend using secrets.GITHUB_TOKEN
    required: true
  tag:
    description: Input tag (Recommend using github.ref_name)
    required: true
  mode:
    description: mode (release or get-packages-info)
    required: true
    default: "release"

  # Release Mode
  title:
    description: Release title or name of the app/package
    required: false
  changelog-file:
    description: Path to the changelog file
    required: false
  dry-run:
    description: Whether to run in dry-run mode
    required: false
    default: "false"

  # Get Packages Info Mode
  packages-info-file:
    description: Path to the file where the packages info is saved
    required: false

# Define your outputs here.
# outputs:
#   time:
#     description: Your output description here

runs:
  using: node20
  main: dist/index.js
