name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Release
        uses: ./
        with:
          mode: "release"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          title: "Release Action"

      - name: Split Version
        id: version
        uses: winterjung/split@v2
        with:
          msg: ${{ github.ref_name }}
          separator: "."

      - name: Update tag of major version
        run: |
          curl -X PATCH \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{\"sha\": \"${{ github.sha }}\", \"force\": true}" \
            https://api.github.com/repos/${{ github.repository }}/git/refs/tags/${{ steps.version.outputs._0}}
